#!/bin/bash
# opd_from_ckpt.sh <base_config> <student_dir> <run_name> [NODES]: OPD/MOPD that starts from another checkpoint (SFT warm-up,
# merged init, another run's ckpt). Clones <base_config> with model.student and train.output replaced
# (-> configs/<kind>/generated/<run_name>.yaml) and submits scripts/opd.sbatch. Teachers come from TEACHERS/WEIGHTS env, or
# by default from the config's data.paths domains -> models/teacher-<domain> (weights 1.0).
#   bash scripts/opd_from_ckpt.sh configs/opd/med_pg.yaml outputs/sft/warmup_med_c6k3_4ep/checkpoint-2164 med_pg_from_warmupB 2
set -u
_here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"; source "${_here}/_common.sh"; cd "${REPO}"
BASE="$1"; CK="$2"; NAME="$3"; NODES="${4:-2}"
[[ -f "${CK}/config.json" && -f "${CK}/model.safetensors.index.json" ]] || { echo "ABORT: ${CK} not loadable"; exit 1; }
KIND="$(basename "$(dirname "${BASE}")")"; mkdir -p "configs/${KIND}/generated"; CFG="configs/${KIND}/generated/${NAME}.yaml"
python3 - "${BASE}" "${CK}" "${NAME}" "${CFG}" <<'PY'
import sys; base, ck, name, cfg = sys.argv[1:5]; out = []
for l in open(base).read().split("\n"):
    if l.startswith("#") and not out: l = f"# generated by scripts/opd_from_ckpt.sh from {base}: student = {ck}"
    if l.strip().startswith("student:"): l = f"  student: {ck}"
    if l.strip().startswith("output:"): l = f"  output: outputs/opd/{name}"
    out.append(l)
open(cfg, "w").write("\n".join(out)); print("config:", cfg)
PY
if [[ -z "${TEACHERS:-}" ]]; then
  T=""; W=""
  for d in $(python3 scripts/cfgval.py "${CFG}" data.paths.KEYS); do T="${T:+${T},}${d}:models/teacher-${d}"; W="${W:+${W},}${d}=1.0"; done
  TEACHERS="${T}"; WEIGHTS="${W}"
fi
J=$(TEACHERS="${TEACHERS}" WEIGHTS="${WEIGHTS:-}" TOPK="${TOPK:-64}" CONFIG="${CFG}" OVERRIDES="" STUDENT_NODES="${STUDENT_NODES:-$((NODES / 2))}" \
    sbatch -N "${NODES}" -J "${JP}-opd-${NAME}" --cpus-per-task=32 --mem=600G -t 48:00:00 $(prefer "${NODES}") --parsable scripts/opd.sbatch)
echo "OPD-SUBMITTED ${J} ${NAME} (teachers ${TEACHERS})"
